fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.13.1
    archive:
      repo: https://github.com/voxpupuli/puppet-archive.git
      ref: v1.0.0
  symlinks:
    phantomjs: "#{source_dir}"
