---
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^v\d
    name: deploy
matrix:
  fast_finish: true
  include:
    -
      bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=centos-7 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: treydock@gmail.com
deploy:
  provider: puppetforge
  user: treydock
  password:
    secure: "TdQ3ibI26WobhDOdR3p434v1JnSa5zQhOT/qGU0/Z+48inoNwUy8KDsraN2vmpsUV9puzu23GkBjs99r19hLkeG36YGWFsUEYGpaLqVbCEmNMXxnHqmsH59hTkewWy6rHCUNME36UMiliwTpHxQkqoGSF3abg9iqXoWjdE/zx3oBbuZOuoLmXgeSRzAt+5FdfWety37OZcqbTAfRtaQXKkNv2aNQ2zPHGgg9lCdXEAAkpBZLd5N7iqO10M8Ug1yGrxmIXqevmvZhV4b86hPphY48yFBAF4hD+e/yvkPfQcy7yM90sbJgvCa4x9PXn8wcGztH42KMNCs5BGk1m2nIL1lMTjn1Ys9Ig9R5R1fsGj2B8T/7YAHudhGV2GCFQPnvH9DqGJGz2ag2H91Gp24J2eCmgxg8D5sfToon1RK67VhdBPMhBm/Z7wr/F/v8TE8GXjP3oQb0f/uvUw7531yDx2gOypzLXj6KRx7xURNd0ii5h178BUIkQ++MkRUh/S+ATEk6WJs4CaVVh0EQ4a+6UyJcGUcdIzaqcFYzIOhF+Dma9K+BsKaT7h3BKnd9wymrHpRJP8KuCS7D4bv9adXjwCeXix3+zzQgq97aXgQz1hd88AK5xnpHQ+gWZ1JYOxtV12TILJEGY4oK34pHhScluMutaCliy/BIml/YIVQtZ+M="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
